// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QUANLYSANBONG.Data;

#nullable disable

namespace QUANLYSANBONG.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604031423_AddMoTaAndHotlineToSanBong")]
    partial class AddMoTaAndHotlineToSanBong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QUANLYSANBONG.Models.BangGiaKhungGio", b =>
                {
                    b.Property<int>("MaBangGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBangGia"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<string>("NgayTrongTuan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("PhuThuCaoDiem")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaBangGia");

                    b.ToTable("BangGiaKhungGio", (string)null);

                    b.HasData(
                        new
                        {
                            MaBangGia = 1,
                            DonGia = 200000m,
                            GioBatDau = new TimeSpan(0, 6, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 8, 0, 0, 0),
                            NgayTrongTuan = "Thu 2 - Thu 6",
                            PhuThuCaoDiem = 0m
                        },
                        new
                        {
                            MaBangGia = 2,
                            DonGia = 300000m,
                            GioBatDau = new TimeSpan(0, 17, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 19, 0, 0, 0),
                            NgayTrongTuan = "Thu 2 - Thu 6",
                            PhuThuCaoDiem = 50000m
                        },
                        new
                        {
                            MaBangGia = 3,
                            DonGia = 350000m,
                            GioBatDau = new TimeSpan(0, 7, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 9, 0, 0, 0),
                            NgayTrongTuan = "Thu 7 - Chu nhat",
                            PhuThuCaoDiem = 50000m
                        });
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.BlogCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BlogCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            MoTa = "Kinh nghiệm kinh doanh sân thể thao",
                            Slug = "kinh-doanh-san",
                            TenDanhMuc = "Kinh doanh sân",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            MoTa = "Cập nhật xu hướng thể thao mới nhất",
                            Slug = "xu-huong",
                            TenDanhMuc = "Xu hướng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 4,
                            MoTa = "Hướng dẫn cho chủ sân và người chơi",
                            Slug = "huong-dan",
                            TenDanhMuc = "Hướng dẫn",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("BlogCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<string>("MoTaNgan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<bool>("NoiBat")
                        .HasColumnType("bit");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ThoiGianDoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BlogCategoryId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("BlogPost", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            BlogCategoryId = 2,
                            LuotXem = 0,
                            MoTaNgan = "Chi phí, vốn và dự toán doanh thu khi kinh doanh sân Pickleball.",
                            NgayDang = new DateTime(2026, 6, 4, 10, 14, 22, 712, DateTimeKind.Local).AddTicks(6163),
                            NoiBat = true,
                            NoiDung = "Nội dung bài viết đang được cập nhật...",
                            Slug = "huong-dan-mo-san-pickleball",
                            ThoiGianDoc = "15 phút đọc",
                            TieuDe = "Hướng Dẫn Mở Sân Pickleball Từ A đến Z",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            BlogCategoryId = 2,
                            LuotXem = 0,
                            MoTaNgan = "Tăng doanh thu 40% trong 3 tháng với các bí quyết quản lý sau.",
                            NgayDang = new DateTime(2026, 6, 4, 10, 14, 22, 712, DateTimeKind.Local).AddTicks(6167),
                            NoiBat = true,
                            NoiDung = "Nội dung bài viết đang được cập nhật...",
                            Slug = "10-cach-quan-ly-san-bong-hieu-qua",
                            ThoiGianDoc = "8 phút đọc",
                            TieuDe = "10 Cách Quản Lý Sân Bóng Hiệu Quả",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 4,
                            BlogCategoryId = 3,
                            LuotXem = 0,
                            MoTaNgan = "Cơ hội vàng cho các chủ đầu tư trong năm 2025.",
                            NgayDang = new DateTime(2026, 6, 4, 10, 14, 22, 712, DateTimeKind.Local).AddTicks(6170),
                            NoiBat = false,
                            NoiDung = "Nội dung bài viết đang được cập nhật...",
                            Slug = "xu-huong-san-pickleball-2025",
                            ThoiGianDoc = "5 phút đọc",
                            TieuDe = "Xu Hướng Sân Pickleball Việt Nam 2025",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 5,
                            BlogCategoryId = 2,
                            LuotXem = 0,
                            MoTaNgan = "Bí quyết tối đa hóa doanh thu cho cơ sở của bạn.",
                            NgayDang = new DateTime(2026, 6, 4, 10, 14, 22, 712, DateTimeKind.Local).AddTicks(6173),
                            NoiBat = false,
                            NoiDung = "Nội dung bài viết đang được cập nhật...",
                            Slug = "cach-tinh-gia-thue-san-bong-da",
                            ThoiGianDoc = "7 phút đọc",
                            TieuDe = "Cách Tính Giá Thuê Sân Bóng Đá Theo Giờ",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 8,
                            BlogCategoryId = 4,
                            LuotXem = 0,
                            MoTaNgan = "Cách ứng dụng công nghệ QR Code để quản lý lượt vào sân chuyên nghiệp.",
                            NgayDang = new DateTime(2026, 6, 4, 10, 14, 22, 712, DateTimeKind.Local).AddTicks(6175),
                            NoiBat = false,
                            NoiDung = "Nội dung bài viết đang được cập nhật...",
                            Slug = "huong-dan-checkin-qr-code",
                            ThoiGianDoc = "4 phút đọc",
                            TieuDe = "Hướng dẫn Check-in Sân Bóng bằng QR Code",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 9,
                            BlogCategoryId = 2,
                            LuotXem = 0,
                            MoTaNgan = "Bảng tính chi tiết vốn đầu tư và thời gian thu hồi vốn.",
                            NgayDang = new DateTime(2026, 6, 4, 10, 14, 22, 712, DateTimeKind.Local).AddTicks(6177),
                            NoiBat = false,
                            NoiDung = "Nội dung bài viết đang được cập nhật...",
                            Slug = "mo-san-bong-da-mini-bao-nhieu-von",
                            ThoiGianDoc = "20 phút đọc",
                            TieuDe = "Mở Sân Bóng Đá Mini Cần Bao Nhiêu Vốn 2026?",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.CaiDatThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangBat")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThongBao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CaiDatThongBao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DangBat = true,
                            Icon = "fas fa-plus-circle",
                            MoTa = "Nhận thông báo khi có khách đặt sân",
                            TenThongBao = "Đặt lịch mới"
                        },
                        new
                        {
                            Id = 2,
                            DangBat = true,
                            Icon = "fas fa-times-circle",
                            MoTa = "Nhận thông báo khi khách hủy lịch đặt",
                            TenThongBao = "Hủy lịch"
                        },
                        new
                        {
                            Id = 3,
                            DangBat = true,
                            Icon = "fas fa-check-double",
                            MoTa = "Nhận thông báo xác nhận thanh toán",
                            TenThongBao = "Thanh toán"
                        },
                        new
                        {
                            Id = 4,
                            DangBat = true,
                            Icon = "fas fa-file-invoice-dollar",
                            MoTa = "Nhận tóm tắt doanh thu cuối ngày",
                            TenThongBao = "Báo cáo ngày"
                        },
                        new
                        {
                            Id = 5,
                            DangBat = true,
                            Icon = "fas fa-tools",
                            MoTa = "Nhắc nhở lịch bảo trì định kỳ",
                            TenThongBao = "Nhắc bảo trì sân"
                        });
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.ChiTietDichVu", b =>
                {
                    b.Property<int>("MaCTDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTDV"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDatSan")
                        .HasColumnType("int");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaCTDV");

                    b.HasIndex("MaDatSan");

                    b.HasIndex("MaDichVu");

                    b.ToTable("ChiTietDichVu", (string)null);
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.DatSan", b =>
                {
                    b.Property<int>("MaDatSan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatSan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<int?>("MaBangGia")
                        .HasColumnType("int");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaSan")
                        .HasColumnType("int");

                    b.Property<int?>("MaSanCon")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<double>("ThoiLuong")
                        .HasColumnType("float");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDatSan");

                    b.HasIndex("MaBangGia");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaSanCon");

                    b.HasIndex("MaSan", "MaBangGia", "NgayDat")
                        .IsUnique()
                        .HasFilter("[TrangThai] <> N'Da huy'");

                    b.ToTable("DatSan", (string)null);
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TonKho")
                        .HasColumnType("int");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVu", (string)null);

                    b.HasData(
                        new
                        {
                            MaDichVu = 1,
                            DonGia = 10000m,
                            DonViTinh = "Chai",
                            TenDichVu = "Nuoc suoi",
                            TonKho = 100
                        },
                        new
                        {
                            MaDichVu = 2,
                            DonGia = 30000m,
                            DonViTinh = "Qua",
                            TenDichVu = "Thue bong",
                            TonKho = 10
                        },
                        new
                        {
                            MaDichVu = 3,
                            DonGia = 50000m,
                            DonViTinh = "Bo",
                            TenDichVu = "Thue ao bib",
                            TonKho = 20
                        });
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.GioHoatDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("GioDongCua")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioMoCua")
                        .HasColumnType("time");

                    b.Property<string>("Thu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GioHoatDong", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DangHoatDong = true,
                            GioDongCua = new TimeSpan(0, 22, 0, 0, 0),
                            GioMoCua = new TimeSpan(0, 6, 0, 0, 0),
                            Thu = "Thứ 2"
                        },
                        new
                        {
                            Id = 2,
                            DangHoatDong = true,
                            GioDongCua = new TimeSpan(0, 22, 0, 0, 0),
                            GioMoCua = new TimeSpan(0, 6, 0, 0, 0),
                            Thu = "Thứ 3"
                        },
                        new
                        {
                            Id = 3,
                            DangHoatDong = true,
                            GioDongCua = new TimeSpan(0, 22, 0, 0, 0),
                            GioMoCua = new TimeSpan(0, 6, 0, 0, 0),
                            Thu = "Thứ 4"
                        },
                        new
                        {
                            Id = 4,
                            DangHoatDong = true,
                            GioDongCua = new TimeSpan(0, 22, 0, 0, 0),
                            GioMoCua = new TimeSpan(0, 6, 0, 0, 0),
                            Thu = "Thứ 5"
                        },
                        new
                        {
                            Id = 5,
                            DangHoatDong = true,
                            GioDongCua = new TimeSpan(0, 22, 0, 0, 0),
                            GioMoCua = new TimeSpan(0, 6, 0, 0, 0),
                            Thu = "Thứ 6"
                        },
                        new
                        {
                            Id = 6,
                            DangHoatDong = true,
                            GioDongCua = new TimeSpan(0, 23, 0, 0, 0),
                            GioMoCua = new TimeSpan(0, 6, 0, 0, 0),
                            Thu = "Thứ 7"
                        },
                        new
                        {
                            Id = 7,
                            DangHoatDong = true,
                            GioDongCua = new TimeSpan(0, 23, 0, 0, 0),
                            GioMoCua = new TimeSpan(0, 6, 0, 0, 0),
                            Thu = "Chủ Nhật"
                        });
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHD"));

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDatSan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhuThu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TienDichVu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienSan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaHD");

                    b.HasIndex("MaDatSan")
                        .IsUnique();

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NhomKhach")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHang", (string)null);

                    b.HasData(
                        new
                        {
                            MaKH = 1,
                            GhiChu = "Hay dat buoi toi",
                            HoTen = "Nguyen Van An",
                            NhomKhach = "Khach quen",
                            SoDienThoai = "0901234567"
                        },
                        new
                        {
                            MaKH = 2,
                            HoTen = "Tran Minh Binh",
                            NhomKhach = "Khach moi",
                            SoDienThoai = "0912345678"
                        });
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.LoaiSan", b =>
                {
                    b.Property<int>("MaLoaiSan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiSan"));

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenLoaiSan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoaiSan");

                    b.ToTable("LoaiSan", (string)null);

                    b.HasData(
                        new
                        {
                            MaLoaiSan = 1,
                            Icon = "fa-futbol",
                            MoTa = "Sân bóng đá",
                            TenLoaiSan = "Bóng đá"
                        },
                        new
                        {
                            MaLoaiSan = 2,
                            Icon = "fa-volleyball",
                            MoTa = "Sân bóng chuyền",
                            TenLoaiSan = "Bóng chuyền"
                        },
                        new
                        {
                            MaLoaiSan = 3,
                            Icon = "fa-basketball",
                            MoTa = "Sân bóng rổ",
                            TenLoaiSan = "Bóng rổ"
                        },
                        new
                        {
                            MaLoaiSan = 4,
                            Icon = "fa-table-tennis-paddle-ball",
                            MoTa = "Bàn bóng bàn",
                            TenLoaiSan = "Bóng bàn"
                        },
                        new
                        {
                            MaLoaiSan = 5,
                            Icon = "fa-baseball",
                            MoTa = "Sân tennis",
                            TenLoaiSan = "Quần vợt"
                        },
                        new
                        {
                            MaLoaiSan = 6,
                            Icon = "fa-table-tennis-paddle-ball",
                            MoTa = "Sân cầu lông",
                            TenLoaiSan = "Cầu lông"
                        },
                        new
                        {
                            MaLoaiSan = 7,
                            Icon = "fa-medal",
                            MoTa = "Sân Pickleball",
                            TenLoaiSan = "Pickleball"
                        });
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);

                    b.HasData(
                        new
                        {
                            MaNguoiDung = 1,
                            Email = "admin@sanbong.vn",
                            HoTen = "Quản trị viên",
                            MaVaiTro = 1,
                            MatKhau = "123456",
                            SoDienThoai = "0888888888",
                            TenDangNhap = "admin",
                            TrangThai = true
                        },
                        new
                        {
                            MaNguoiDung = 2,
                            Email = "nhanvien@sanbong.vn",
                            HoTen = "Nhân viên",
                            MaVaiTro = 3,
                            MatKhau = "123456",
                            SoDienThoai = "0888111222",
                            TenDangNhap = "nhanvien",
                            TrangThai = true
                        },
                        new
                        {
                            MaNguoiDung = 3,
                            Email = "ketoan@sanbong.vn",
                            HoTen = "Kế toán",
                            MaVaiTro = 4,
                            MatKhau = "123456",
                            SoDienThoai = "0888333444",
                            TenDangNhap = "ketoan",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique()
                        .HasFilter("[MaNguoiDung] IS NOT NULL");

                    b.ToTable("NhanVien", (string)null);

                    b.HasData(
                        new
                        {
                            MaNV = 1,
                            ChucVu = "Admin",
                            Email = "admin@sanbong.local",
                            HoTen = "Quan tri vien",
                            MaNguoiDung = 1,
                            SoDienThoai = "0900000000"
                        },
                        new
                        {
                            MaNV = 2,
                            ChucVu = "Nhan vien",
                            Email = "nhanvien@sanbong.local",
                            HoTen = "Nhan vien san",
                            MaNguoiDung = 2,
                            SoDienThoai = "0911111111"
                        },
                        new
                        {
                            MaNV = 3,
                            ChucVu = "Ke toan",
                            Email = "ketoan@sanbong.local",
                            HoTen = "Nhan vien ke toan",
                            MaNguoiDung = 3,
                            SoDienThoai = "0922222222"
                        });
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.NhatKyThaoTac", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("NhatKyThaoTac", (string)null);
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.SanBong", b =>
                {
                    b.Property<int>("MaSan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSan"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("GiaMacDinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("MaLoaiSan")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("SoLuongSanCon")
                        .HasColumnType("int");

                    b.Property<string>("TenSan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhThanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaSan");

                    b.HasIndex("MaLoaiSan");

                    b.ToTable("SanBong", (string)null);

                    b.HasData(
                        new
                        {
                            MaSan = 1,
                            DiaChi = "Thủ Đức, Hồ Chí Minh",
                            GiaMacDinh = 250000m,
                            HinhAnh = "https://images.unsplash.com/photo-1518605368461-1ee7e1273932?q=80&w=2070&auto=format&fit=crop",
                            Latitude = 10.849399999999999,
                            Longitude = 106.75369999999999,
                            MaLoaiSan = 7,
                            SoLuongSanCon = 2,
                            TenSan = "002 PB Club",
                            TinhThanh = "TP. Hồ Chí Minh",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 2,
                            DiaChi = "Quận 8, Hồ Chí Minh",
                            GiaMacDinh = 200000m,
                            HinhAnh = "https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop",
                            Latitude = 10.7415,
                            Longitude = 106.63420000000001,
                            MaLoaiSan = 7,
                            SoLuongSanCon = 2,
                            TenSan = "ST PB Club Q8",
                            TinhThanh = "TP. Hồ Chí Minh",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 3,
                            DiaChi = "Quận 8, Hồ Chí Minh",
                            GiaMacDinh = 220000m,
                            HinhAnh = "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?q=80&w=2070&auto=format&fit=crop",
                            Latitude = 10.7356,
                            Longitude = 106.661,
                            MaLoaiSan = 1,
                            SoLuongSanCon = 1,
                            TenSan = "9196 Sport Q8",
                            TinhThanh = "TP. Hồ Chí Minh",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 4,
                            DiaChi = "Đống Đa, Hà Nội",
                            GiaMacDinh = 300000m,
                            HinhAnh = "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?q=80&w=2069&auto=format&fit=crop",
                            Latitude = 21.0123,
                            Longitude = 105.8284,
                            MaLoaiSan = 7,
                            SoLuongSanCon = 2,
                            TenSan = "ACE PB Club",
                            TinhThanh = "Hà Nội",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 5,
                            DiaChi = "Thủ Đức, Hồ Chí Minh",
                            GiaMacDinh = 200000m,
                            HinhAnh = "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?q=80&w=2070&auto=format&fit=crop",
                            Latitude = 10.8307,
                            Longitude = 106.82040000000001,
                            MaLoaiSan = 7,
                            SoLuongSanCon = 1,
                            TenSan = "Apec PB Q9",
                            TinhThanh = "TP. Hồ Chí Minh",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 6,
                            DiaChi = "Tân Bình, Hồ Chí Minh",
                            GiaMacDinh = 300000m,
                            HinhAnh = "https://images.unsplash.com/photo-1518605368461-1ee7e1273932?q=80&w=2070&auto=format&fit=crop",
                            Latitude = 10.8032,
                            Longitude = 106.6433,
                            MaLoaiSan = 1,
                            SoLuongSanCon = 5,
                            TenSan = "Sân Bóng Chảo Lửa",
                            TinhThanh = "TP. Hồ Chí Minh",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 7,
                            DiaChi = "Cầu Giấy, Hà Nội",
                            GiaMacDinh = 400000m,
                            HinhAnh = "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?q=80&w=2070&auto=format&fit=crop",
                            Latitude = 21.036200000000001,
                            Longitude = 105.7906,
                            MaLoaiSan = 5,
                            SoLuongSanCon = 3,
                            TenSan = "Tennis Phượng Hoàng",
                            TinhThanh = "Hà Nội",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 8,
                            DiaChi = "Tân Phú, Hồ Chí Minh",
                            GiaMacDinh = 150000m,
                            HinhAnh = "https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop",
                            Latitude = 10.791499999999999,
                            Longitude = 106.63420000000001,
                            MaLoaiSan = 6,
                            SoLuongSanCon = 8,
                            TenSan = "Nhà thi đấu Cầu Lông Tân Phú",
                            TinhThanh = "TP. Hồ Chí Minh",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 9,
                            DiaChi = "Quận 1, Hồ Chí Minh",
                            GiaMacDinh = 250000m,
                            HinhAnh = "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?q=80&w=2069&auto=format&fit=crop",
                            Latitude = 10.7828,
                            Longitude = 106.69580000000001,
                            MaLoaiSan = 3,
                            SoLuongSanCon = 2,
                            TenSan = "Sân Bóng Rổ Thanh Niên",
                            TinhThanh = "TP. Hồ Chí Minh",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 10,
                            DiaChi = "Gò Vấp, Hồ Chí Minh",
                            GiaMacDinh = 200000m,
                            HinhAnh = "https://images.unsplash.com/photo-1518605368461-1ee7e1273932?q=80&w=2070&auto=format&fit=crop",
                            Latitude = 10.8203,
                            Longitude = 106.67149999999999,
                            MaLoaiSan = 1,
                            SoLuongSanCon = 4,
                            TenSan = "Sân Cỏ Nhân Tạo K34",
                            TinhThanh = "TP. Hồ Chí Minh",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 11,
                            DiaChi = "Ba Đình, Hà Nội",
                            GiaMacDinh = 350000m,
                            HinhAnh = "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?q=80&w=2070&auto=format&fit=crop",
                            Latitude = 21.037800000000001,
                            Longitude = 105.8156,
                            MaLoaiSan = 5,
                            SoLuongSanCon = 2,
                            TenSan = "Sân Tennis Hoàng Hoa Thám",
                            TinhThanh = "Hà Nội",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 12,
                            DiaChi = "Tân Bình, Hồ Chí Minh",
                            GiaMacDinh = 160000m,
                            HinhAnh = "https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop",
                            Latitude = 10.785399999999999,
                            Longitude = 106.6631,
                            MaLoaiSan = 6,
                            SoLuongSanCon = 6,
                            TenSan = "Cầu Lông Lê Thị Riêng",
                            TinhThanh = "TP. Hồ Chí Minh",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 13,
                            DiaChi = "Sơn Trà, Đà Nẵng",
                            GiaMacDinh = 300000m,
                            HinhAnh = "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?q=80&w=2069&auto=format&fit=crop",
                            Latitude = 16.0748,
                            Longitude = 108.2435,
                            MaLoaiSan = 2,
                            SoLuongSanCon = 1,
                            TenSan = "Bóng Chuyền Bãi Biển",
                            TinhThanh = "Đà Nẵng",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 14,
                            DiaChi = "Nam Từ Liêm, Hà Nội",
                            GiaMacDinh = 5000000m,
                            HinhAnh = "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?q=80&w=2070&auto=format&fit=crop",
                            Latitude = 21.020299999999999,
                            Longitude = 105.76390000000001,
                            MaLoaiSan = 1,
                            SoLuongSanCon = 1,
                            TenSan = "Sân Vận Động Mỹ Đình",
                            TinhThanh = "Hà Nội",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 15,
                            DiaChi = "Quận 5, Hồ Chí Minh",
                            GiaMacDinh = 100000m,
                            HinhAnh = "https://images.unsplash.com/photo-1518605368461-1ee7e1273932?q=80&w=2070&auto=format&fit=crop",
                            Latitude = 10.754200000000001,
                            Longitude = 106.6635,
                            MaLoaiSan = 4,
                            SoLuongSanCon = 10,
                            TenSan = "CLB Bóng Bàn Quận 5",
                            TinhThanh = "TP. Hồ Chí Minh",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 16,
                            DiaChi = "Quận 1, Hồ Chí Minh",
                            GiaMacDinh = 220000m,
                            HinhAnh = "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?q=80&w=2069&auto=format&fit=crop",
                            Latitude = 10.776899999999999,
                            Longitude = 106.69540000000001,
                            MaLoaiSan = 3,
                            SoLuongSanCon = 2,
                            TenSan = "Bóng Rổ Yết Kiêu",
                            TinhThanh = "TP. Hồ Chí Minh",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 17,
                            DiaChi = "Ninh Kiều, Cần Thơ",
                            GiaMacDinh = 200000m,
                            HinhAnh = "https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop",
                            Latitude = 10.0342,
                            Longitude = 105.78279999999999,
                            MaLoaiSan = 1,
                            SoLuongSanCon = 3,
                            TenSan = "Sân Bóng Đá Cần Thơ",
                            TinhThanh = "Cần Thơ",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 18,
                            DiaChi = "Quận 10, Hồ Chí Minh",
                            GiaMacDinh = 250000m,
                            HinhAnh = "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?q=80&w=2070&auto=format&fit=crop",
                            Latitude = 10.776400000000001,
                            Longitude = 106.6698,
                            MaLoaiSan = 7,
                            SoLuongSanCon = 4,
                            TenSan = "Pickleball Vạn Hạnh",
                            TinhThanh = "TP. Hồ Chí Minh",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 19,
                            DiaChi = "Lê Chân, Hải Phòng",
                            GiaMacDinh = 180000m,
                            HinhAnh = "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?q=80&w=2070&auto=format&fit=crop",
                            Latitude = 20.844899999999999,
                            Longitude = 106.68810000000001,
                            MaLoaiSan = 1,
                            SoLuongSanCon = 2,
                            TenSan = "Sân Bóng Hải Phòng",
                            TinhThanh = "Hải Phòng",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSan = 20,
                            DiaChi = "Thủ Dầu Một, Bình Dương",
                            GiaMacDinh = 120000m,
                            HinhAnh = "https://images.unsplash.com/photo-1518605368461-1ee7e1273932?q=80&w=2070&auto=format&fit=crop",
                            Latitude = 10.980399999999999,
                            Longitude = 106.6519,
                            MaLoaiSan = 6,
                            SoLuongSanCon = 5,
                            TenSan = "Cầu Lông Bình Dương",
                            TinhThanh = "Bình Dương",
                            TrangThai = "Hoat dong"
                        });
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.SanCon", b =>
                {
                    b.Property<int>("MaSanCon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanCon"));

                    b.Property<int>("MaSan")
                        .HasColumnType("int");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenSanCon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaSanCon");

                    b.HasIndex("MaSan");

                    b.ToTable("SanCon");

                    b.HasData(
                        new
                        {
                            MaSanCon = 1,
                            MaSan = 1,
                            SucChua = 4,
                            TenSanCon = "Sân PB1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 2,
                            MaSan = 1,
                            SucChua = 4,
                            TenSanCon = "Sân PB2",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 3,
                            MaSan = 2,
                            SucChua = 4,
                            TenSanCon = "Sân PB1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 4,
                            MaSan = 2,
                            SucChua = 4,
                            TenSanCon = "Sân PB2",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 5,
                            MaSan = 3,
                            SucChua = 10,
                            TenSanCon = "Sân 5 số 1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 6,
                            MaSan = 4,
                            SucChua = 4,
                            TenSanCon = "Sân PB1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 7,
                            MaSan = 4,
                            SucChua = 4,
                            TenSanCon = "Sân PB2",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 8,
                            MaSan = 5,
                            SucChua = 4,
                            TenSanCon = "Sân PB1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 9,
                            MaSan = 6,
                            SucChua = 10,
                            TenSanCon = "Sân 5 số 1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 10,
                            MaSan = 6,
                            SucChua = 10,
                            TenSanCon = "Sân 5 số 2",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 11,
                            MaSan = 7,
                            SucChua = 4,
                            TenSanCon = "Sân Tennis 1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 12,
                            MaSan = 7,
                            SucChua = 4,
                            TenSanCon = "Sân Tennis 2",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 13,
                            MaSan = 8,
                            SucChua = 4,
                            TenSanCon = "Sân Cầu Lông 1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 14,
                            MaSan = 8,
                            SucChua = 4,
                            TenSanCon = "Sân Cầu Lông 2",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 15,
                            MaSan = 9,
                            SucChua = 10,
                            TenSanCon = "Sân Bóng Rổ 1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 16,
                            MaSan = 10,
                            SucChua = 10,
                            TenSanCon = "Sân 5 số 1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 17,
                            MaSan = 11,
                            SucChua = 4,
                            TenSanCon = "Sân Tennis 1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 18,
                            MaSan = 12,
                            SucChua = 4,
                            TenSanCon = "Sân Cầu Lông 1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 19,
                            MaSan = 13,
                            SucChua = 12,
                            TenSanCon = "Sân Bóng Chuyền 1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 20,
                            MaSan = 14,
                            SucChua = 22,
                            TenSanCon = "Sân 11",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 21,
                            MaSan = 15,
                            SucChua = 2,
                            TenSanCon = "Bàn 1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 22,
                            MaSan = 16,
                            SucChua = 10,
                            TenSanCon = "Sân Bóng Rổ 1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 23,
                            MaSan = 17,
                            SucChua = 10,
                            TenSanCon = "Sân 5 số 1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 24,
                            MaSan = 18,
                            SucChua = 4,
                            TenSanCon = "Sân PB1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 25,
                            MaSan = 19,
                            SucChua = 10,
                            TenSanCon = "Sân 5 số 1",
                            TrangThai = "Hoat dong"
                        },
                        new
                        {
                            MaSanCon = 26,
                            MaSan = 20,
                            SucChua = 4,
                            TenSanCon = "Sân Cầu Lông 1",
                            TrangThai = "Hoat dong"
                        });
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.ThongTinSan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThongTinSan", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiaChi = "Linh Trung, Thu Duc, TP.HCM",
                            Email = "contact@sanbong.vn",
                            MoTa = "He thong quan ly san bong chuyen nghiep",
                            SoDienThoai = "0888888888",
                            TenSan = "SanBong.vn",
                            Website = "www.sanbong.vn"
                        });
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro", (string)null);

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            MoTa = "Quan tri he thong",
                            TenVaiTro = "Admin"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            MoTa = "Quan ly san bong",
                            TenVaiTro = "Quan ly"
                        },
                        new
                        {
                            MaVaiTro = 3,
                            MoTa = "Nhan vien dat san va dich vu",
                            TenVaiTro = "Nhan vien"
                        },
                        new
                        {
                            MaVaiTro = 4,
                            MoTa = "Thanh toan va bao cao",
                            TenVaiTro = "Ke toan"
                        },
                        new
                        {
                            MaVaiTro = 5,
                            MoTa = "Khach hang dat san",
                            TenVaiTro = "Khach hang"
                        });
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.BlogPost", b =>
                {
                    b.HasOne("QUANLYSANBONG.Models.BlogCategory", "Category")
                        .WithMany("BlogPosts")
                        .HasForeignKey("BlogCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QUANLYSANBONG.Models.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId");

                    b.Navigation("Category");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.ChiTietDichVu", b =>
                {
                    b.HasOne("QUANLYSANBONG.Models.DatSan", "DatSan")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaDatSan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QUANLYSANBONG.Models.DichVu", "DichVu")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatSan");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.DatSan", b =>
                {
                    b.HasOne("QUANLYSANBONG.Models.BangGiaKhungGio", "BangGiaKhungGio")
                        .WithMany("DatSans")
                        .HasForeignKey("MaBangGia")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QUANLYSANBONG.Models.KhachHang", "KhachHang")
                        .WithMany("DatSans")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QUANLYSANBONG.Models.SanBong", "SanBong")
                        .WithMany("DatSans")
                        .HasForeignKey("MaSan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QUANLYSANBONG.Models.SanCon", "SanCon")
                        .WithMany()
                        .HasForeignKey("MaSanCon")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BangGiaKhungGio");

                    b.Navigation("KhachHang");

                    b.Navigation("SanBong");

                    b.Navigation("SanCon");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.HoaDon", b =>
                {
                    b.HasOne("QUANLYSANBONG.Models.DatSan", "DatSan")
                        .WithOne("HoaDon")
                        .HasForeignKey("QUANLYSANBONG.Models.HoaDon", "MaDatSan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatSan");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.NguoiDung", b =>
                {
                    b.HasOne("QUANLYSANBONG.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.NhanVien", b =>
                {
                    b.HasOne("QUANLYSANBONG.Models.NguoiDung", "NguoiDung")
                        .WithOne("NhanVien")
                        .HasForeignKey("QUANLYSANBONG.Models.NhanVien", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.NhatKyThaoTac", b =>
                {
                    b.HasOne("QUANLYSANBONG.Models.NguoiDung", "NguoiDung")
                        .WithMany("NhatKyThaoTacs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.SanBong", b =>
                {
                    b.HasOne("QUANLYSANBONG.Models.LoaiSan", "LoaiSan")
                        .WithMany("SanBongs")
                        .HasForeignKey("MaLoaiSan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiSan");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.SanCon", b =>
                {
                    b.HasOne("QUANLYSANBONG.Models.SanBong", "SanBong")
                        .WithMany("SanCons")
                        .HasForeignKey("MaSan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanBong");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.BangGiaKhungGio", b =>
                {
                    b.Navigation("DatSans");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.BlogCategory", b =>
                {
                    b.Navigation("BlogPosts");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.DatSan", b =>
                {
                    b.Navigation("ChiTietDichVus");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.DichVu", b =>
                {
                    b.Navigation("ChiTietDichVus");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.KhachHang", b =>
                {
                    b.Navigation("DatSans");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.LoaiSan", b =>
                {
                    b.Navigation("SanBongs");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.NguoiDung", b =>
                {
                    b.Navigation("NhanVien");

                    b.Navigation("NhatKyThaoTacs");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.SanBong", b =>
                {
                    b.Navigation("DatSans");

                    b.Navigation("SanCons");
                });

            modelBuilder.Entity("QUANLYSANBONG.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
